"""Debug the event-HDF5 -> SpikeNet preprocessing flow.

The script checks three layers:
1. Event HDF5 exported by ``spkData/export_hdf5_events.py``.
2. SpikeNet ``*_in.h5`` generated by ``translation.spikenet_preprocessing``.
3. Compatibility between event coordinates and the network grid.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import h5py
import matplotlib
import numpy as np

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from spkData.export_hdf5_events import write_event_hdf5  # noqa: E402
from translation.spikenet_preprocessing import (  # noqa: E402
    ChenGong2019Config,
    build_chen_gong_2019_input,
)


@dataclass
class Check:
    level: str
    name: str
    detail: str


class Report:
    def __init__(self) -> None:
        self.checks: list[Check] = []

    def pass_(self, name: str, detail: str) -> None:
        self.checks.append(Check("PASS", name, detail))

    def warn(self, name: str, detail: str) -> None:
        self.checks.append(Check("WARN", name, detail))

    def fail(self, name: str, detail: str) -> None:
        self.checks.append(Check("FAIL", name, detail))

    @property
    def failed(self) -> bool:
        return any(c.level == "FAIL" for c in self.checks)

    def print(self) -> None:
        for check in self.checks:
            print(f"[{check.level}] {check.name}: {check.detail}")


def _decode_h5_scalar(value: Any) -> Any:
    if isinstance(value, bytes):
        return value.decode("utf-8")
    if isinstance(value, np.ndarray) and value.shape == ():
        return _decode_h5_scalar(value[()])
    if isinstance(value, np.generic):
        return value.item()
    return value


def _read_dataset(h5f: h5py.File, name: str, report: Report) -> np.ndarray | None:
    if name not in h5f:
        report.fail(f"event dataset {name}", "missing")
        return None
    arr = h5f[name][()]
    if np.asarray(arr).ndim != 1:
        report.fail(f"event dataset {name}", f"expected 1-D, got shape {np.asarray(arr).shape}")
        return None
    return np.asarray(arr)


def inspect_event_file(path: Path, report: Report) -> dict[str, Any] | None:
    if not path.exists():
        report.fail("event file exists", str(path))
        return None

    with h5py.File(path, "r") as h5f:
        x = _read_dataset(h5f, "x", report)
        y = _read_dataset(h5f, "y", report)
        t = _read_dataset(h5f, "t", report)
        pol = _read_dataset(h5f, "pol", report)
        if any(v is None for v in (x, y, t, pol)):
            return None
        assert x is not None and y is not None and t is not None and pol is not None

        lengths = {len(x), len(y), len(t), len(pol)}
        if len(lengths) == 1:
            report.pass_("event lengths", f"{len(x)} events")
        else:
            report.fail("event lengths", f"x/y/t/pol lengths differ: {sorted(lengths)}")

        attrs = {k: _decode_h5_scalar(v) for k, v in h5f.attrs.items()}
        frames_shape = attrs.get("frames_shape")
        dt = attrs.get("dt")
        start_time = attrs.get("start_time")
        if frames_shape is None:
            report.warn("event attr frames_shape", "missing; coordinate bounds will be inferred from x/y")
        else:
            report.pass_("event attr frames_shape", str(tuple(np.asarray(frames_shape).tolist())))
        if dt is None:
            report.warn("event attr dt", "missing")
        else:
            report.pass_("event attr dt", str(dt))
        if start_time is None:
            report.warn("event attr start_time", "missing")
        else:
            report.pass_("event attr start_time", str(start_time))

        if len(x) > 0:
            summary = {
                "path": str(path),
                "num_events": int(len(x)),
                "x_min": int(np.min(x)),
                "x_max": int(np.max(x)),
                "y_min": int(np.min(y)),
                "y_max": int(np.max(y)),
                "t_min": float(np.min(t)),
                "t_max": float(np.max(t)),
                "pol_counts": {str(k): int(v) for k, v in zip(*np.unique(pol, return_counts=True))},
                "frames_shape": None if frames_shape is None else tuple(int(v) for v in np.asarray(frames_shape)),
                "dt": dt,
                "start_time": start_time,
            }
            report.pass_(
                "event coordinate/time ranges",
                f"x=[{summary['x_min']},{summary['x_max']}], "
                f"y=[{summary['y_min']},{summary['y_max']}], "
                f"t=[{summary['t_min']},{summary['t_max']}]",
            )
        else:
            summary = {
                "path": str(path),
                "num_events": 0,
                "x_min": None,
                "x_max": None,
                "y_min": None,
                "y_max": None,
                "t_min": None,
                "t_max": None,
                "pol_counts": {},
                "frames_shape": None if frames_shape is None else tuple(int(v) for v in np.asarray(frames_shape)),
                "dt": dt,
                "start_time": start_time,
            }
            report.warn("event coordinate/time ranges", "file contains zero events")

    return summary


def event_frames(path: Path, *, max_frames: int = 8, bins: int | None = None) -> tuple[np.ndarray, np.ndarray]:
    with h5py.File(path, "r") as h5f:
        x = np.asarray(h5f["x"][()])
        y = np.asarray(h5f["y"][()])
        t = np.asarray(h5f["t"][()])
        shape_attr = h5f.attrs.get("frames_shape")

    if shape_attr is not None and len(shape_attr) == 3:
        _, height, width = (int(v) for v in shape_attr)
    else:
        height = int(y.max()) + 1 if y.size else 1
        width = int(x.max()) + 1 if x.size else 1

    if t.size == 0:
        return np.zeros((1, height, width), dtype=np.float32), np.asarray([0])

    unique_t = np.unique(t)
    if bins is None and unique_t.size <= max_frames:
        selected = unique_t[:max_frames]
        frames = np.zeros((selected.size, height, width), dtype=np.float32)
        for idx, ts in enumerate(selected):
            mask = t == ts
            np.add.at(frames[idx], (y[mask].astype(int), x[mask].astype(int)), 1)
        return frames, selected

    bins = bins or max_frames
    edges = np.linspace(float(t.min()), float(t.max()) + 1e-9, bins + 1)
    frames = np.zeros((bins, height, width), dtype=np.float32)
    bin_idx = np.clip(np.searchsorted(edges, t, side="right") - 1, 0, bins - 1)
    for idx in range(bins):
        mask = bin_idx == idx
        if np.any(mask):
            np.add.at(frames[idx], (y[mask].astype(int), x[mask].astype(int)), 1)
    return frames, edges[:-1]


def save_event_preview(path: Path, output_png: Path, *, max_frames: int = 8) -> None:
    frames, labels = event_frames(path, max_frames=max_frames)
    cols = min(4, frames.shape[0])
    rows = int(np.ceil(frames.shape[0] / cols))
    fig, axes = plt.subplots(rows, cols, figsize=(3 * cols, 3 * rows), squeeze=False)
    vmax = max(float(frames.max()), 1.0)
    for idx, ax in enumerate(axes.flat):
        ax.axis("off")
        if idx >= frames.shape[0]:
            continue
        ax.imshow(frames[idx], cmap="magma", vmin=0, vmax=vmax)
        ax.set_title(f"t/bin {labels[idx]:g}")
    output_png.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(output_png, dpi=140)
    plt.close(fig)


def h5_tree(path: Path, *, max_items: int = 80) -> list[str]:
    lines: list[str] = []

    def visitor(name: str, obj) -> None:
        if len(lines) >= max_items:
            return
        if isinstance(obj, h5py.Dataset):
            lines.append(f"/{name} shape={obj.shape} dtype={obj.dtype}")
        else:
            lines.append(f"/{name}/")

    with h5py.File(path, "r") as h5f:
        h5f.visititems(visitor)
    if len(lines) >= max_items:
        lines.append(f"... truncated at {max_items} items")
    return lines


def inspect_in_file(path: Path, event_e: Path, event_i: Path, report: Report) -> dict[str, Any] | None:
    if not path.exists():
        report.fail("preprocessing in.h5 exists", str(path))
        return None

    required = [
        "/config/pops/pop0/file_current_input/fname",
        "/config/pops/pop1/file_current_input/fname",
        "/config/Net/INIT001/N",
        "/config/Net/INIT002/dt",
        "/config/Net/INIT002/step_tot",
        "/config/syns/n_syns",
    ]
    summary: dict[str, Any] = {"path": str(path)}
    with h5py.File(path, "r") as h5f:
        for dataset in required:
            if dataset in h5f:
                report.pass_(f"in.h5 dataset {dataset}", f"shape={h5f[dataset].shape}")
            else:
                report.fail(f"in.h5 dataset {dataset}", "missing")

        if "/config/pops/pop0/file_current_input/fname" in h5f:
            fname0 = _decode_h5_scalar(h5f["/config/pops/pop0/file_current_input/fname"][()][0])
            summary["pop0_fname"] = fname0
            if Path(fname0) == event_e:
                report.pass_("pop0 input path", fname0)
            else:
                report.warn("pop0 input path", f"stored {fname0}, expected {event_e}")
        if "/config/pops/pop1/file_current_input/fname" in h5f:
            fname1 = _decode_h5_scalar(h5f["/config/pops/pop1/file_current_input/fname"][()][0])
            summary["pop1_fname"] = fname1
            if Path(fname1) == event_i:
                report.pass_("pop1 input path", fname1)
            else:
                report.warn("pop1 input path", f"stored {fname1}, expected {event_i}")

        if "/config/Net/INIT001/N" in h5f:
            n = np.asarray(h5f["/config/Net/INIT001/N"][()], dtype=int)
            summary["N"] = n.tolist()
        if "/config/Net/INIT002/dt" in h5f:
            summary["dt"] = float(h5f["/config/Net/INIT002/dt"][()])
        if "/config/Net/INIT002/step_tot" in h5f:
            summary["step_tot"] = int(h5f["/config/Net/INIT002/step_tot"][()])
        if "/config/syns/n_syns" in h5f:
            n_syns = int(h5f["/config/syns/n_syns"][()])
            summary["n_syns"] = n_syns
            if n_syns == 4:
                report.pass_("synapse block count", "4 population-pair blocks")
            else:
                report.warn("synapse block count", f"{n_syns} blocks")
            syn_summaries = []
            for idx in range(n_syns):
                base = f"/config/syns/syn{idx}/INIT006"
                missing = [leaf for leaf in ("type", "i_pre", "j_post", "I", "J", "K", "D") if f"{base}/{leaf}" not in h5f]
                if missing:
                    report.fail(f"syn{idx} datasets", f"missing {missing}")
                    continue
                syn_type = int(h5f[f"{base}/type"][()])
                pop_pre = int(h5f[f"{base}/i_pre"][()])
                pop_post = int(h5f[f"{base}/j_post"][()])
                i = np.asarray(h5f[f"{base}/I"][()])
                j = np.asarray(h5f[f"{base}/J"][()])
                k = np.asarray(h5f[f"{base}/K"][()])
                d = np.asarray(h5f[f"{base}/D"][()])
                if len({len(i), len(j), len(k), len(d)}) == 1:
                    report.pass_(f"syn{idx} I/J/K/D lengths", str(len(i)))
                else:
                    report.fail(f"syn{idx} I/J/K/D lengths", f"{len(i)}, {len(j)}, {len(k)}, {len(d)}")
                if "N" in summary and 0 <= pop_pre < len(summary["N"]) and 0 <= pop_post < len(summary["N"]):
                    i_ok = i.size == 0 or (int(i.min()) >= 0 and int(i.max()) < int(summary["N"][pop_pre]))
                    j_ok = j.size == 0 or (int(j.min()) >= 0 and int(j.max()) < int(summary["N"][pop_post]))
                    if i_ok and j_ok:
                        report.pass_(
                            f"syn{idx} 0-based bounds",
                            f"type={syn_type}, pop{pop_pre}->pop{pop_post}, "
                            f"I in [0,{int(summary['N'][pop_pre]) - 1}], J in [0,{int(summary['N'][pop_post]) - 1}]",
                        )
                    else:
                        report.fail(
                            f"syn{idx} 0-based bounds",
                            f"pop{pop_pre}->pop{pop_post}, I=[{i.min() if i.size else None},{i.max() if i.size else None}], "
                            f"J=[{j.min() if j.size else None},{j.max() if j.size else None}]",
                        )
                syn_summaries.append(
                    {
                        "syn": idx,
                        "type": syn_type,
                        "pop_pre": pop_pre,
                        "pop_post": pop_post,
                        "count": int(len(i)),
                        "k_min": None if k.size == 0 else float(k.min()),
                        "k_max": None if k.size == 0 else float(k.max()),
                    }
                )
            summary["synapses"] = syn_summaries

    return summary


def check_population_match(event_summary: dict[str, Any], grid_shape: tuple[int, int], report: Report) -> None:
    grid_h, grid_w = int(grid_shape[0]), int(grid_shape[1])
    if event_summary["num_events"] == 0:
        report.warn("event/grid match", "zero-event file cannot validate coordinate coverage")
        return

    x_ok = 0 <= event_summary["x_min"] and event_summary["x_max"] < grid_w
    y_ok = 0 <= event_summary["y_min"] and event_summary["y_max"] < grid_h
    if x_ok and y_ok:
        report.pass_("event/grid coordinate match", f"x within [0,{grid_w - 1}], y within [0,{grid_h - 1}]")
    else:
        report.fail(
            "event/grid coordinate match",
            f"x=[{event_summary['x_min']},{event_summary['x_max']}], "
            f"y=[{event_summary['y_min']},{event_summary['y_max']}], grid={grid_h}x{grid_w}",
        )

    shape = event_summary.get("frames_shape")
    if shape and len(shape) == 3:
        _, height, width = shape
        if height == grid_h and width == grid_w:
            report.pass_("frames_shape/grid match", f"{height}x{width}")
        else:
            report.warn(
                "frames_shape/grid match",
                f"frames are {height}x{width}, network grid is {grid_h}x{grid_w}; "
                "需要确认 simulator 如何把事件坐标映射到 neuron index",
            )


def infer_grid_shape(event_summary: dict[str, Any] | None, explicit: tuple[int, int] | None, fallback_gsize: int) -> tuple[int, int]:
    if explicit is not None:
        return explicit
    if event_summary is not None:
        shape = event_summary.get("frames_shape")
        if shape and len(shape) == 3:
            return int(shape[1]), int(shape[2])
    return int(fallback_gsize), int(fallback_gsize)


def make_synthetic_event_file(path: Path, *, frames: int, height: int, width: int) -> Path:
    data = np.zeros((frames, height, width), dtype=np.uint8)
    box_h = max(2, height // 6)
    box_w = max(2, width // 6)
    max_y = max(1, height - box_h)
    max_x = max(1, width - box_w)
    for t in range(frames):
        y0 = int(round(t * max_y / max(frames - 1, 1)))
        x0 = int(round(t * max_x / max(frames - 1, 1)))
        data[t, y0 : y0 + box_h, x0 : x0 + box_w] = 1
    write_event_hdf5(path, data, dt=1, start_time=0, threshold=0, pol_value=1)
    return path


def write_json_report(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--event-e", type=Path, help="Event HDF5 for excitatory population.")
    parser.add_argument("--event-i", type=Path, help="Event HDF5 for inhibitory population. Defaults to --event-e.")
    parser.add_argument("--make-synthetic", action="store_true", help="Generate a moving-box event HDF5 before debugging.")
    parser.add_argument("--synthetic-frames", type=int, default=12)
    parser.add_argument("--synthetic-height", type=int, default=16)
    parser.add_argument("--synthetic-width", type=int, default=16)
    parser.add_argument("--output-dir", type=Path, default=Path("translation/debug_outputs"))
    parser.add_argument("--gsize", type=int, default=16, help="Fallback square grid size.")
    parser.add_argument("--grid-shape", nargs=2, type=int, metavar=("HEIGHT", "WIDTH"), help="Override rectangular grid shape.")
    parser.add_argument("--step-tot", type=int, default=25000)
    parser.add_argument("--connection-backend", choices=("auto", "torch", "numpy"), default="auto")
    parser.add_argument("--connection-device", default="auto", help="auto, cpu, cuda, cuda:0, ...")
    parser.add_argument("--preview-frames", type=int, default=8)
    parser.add_argument("--skip-build", action="store_true", help="Only inspect event files, do not build *_in.h5.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    report = Report()
    output_dir = args.output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    event_e = args.event_e
    if args.make_synthetic:
        event_e = output_dir / "synthetic_moving_box_E.h5"
        make_synthetic_event_file(
            event_e,
            frames=args.synthetic_frames,
            height=args.synthetic_height,
            width=args.synthetic_width,
        )
        report.pass_("synthetic event file", str(event_e))

    if event_e is None:
        report.fail("event input", "provide --event-e or use --make-synthetic")
        report.print()
        return 1

    event_i = args.event_i or event_e
    event_summary_e = inspect_event_file(event_e, report)
    event_summary_i = inspect_event_file(event_i, report) if event_i != event_e else event_summary_e
    explicit_grid_shape = None if args.grid_shape is None else tuple(args.grid_shape)
    grid_shape = infer_grid_shape(event_summary_e, explicit_grid_shape, args.gsize)
    if event_summary_e is not None:
        preview_path = output_dir / f"{event_e.stem}_preview.png"
        save_event_preview(event_e, preview_path, max_frames=args.preview_frames)
        report.pass_("event preview image", str(preview_path))
        check_population_match(event_summary_e, grid_shape, report)

    in_summary = None
    in_path = output_dir / "debug_spikenet_in.h5"
    if not args.skip_build and event_summary_e is not None and event_summary_i is not None:
        cfg = ChenGong2019Config(
            gsize=args.gsize,
            grid_shape=grid_shape,
            step_tot=args.step_tot,
            connection_backend=args.connection_backend,
            connection_device=args.connection_device,
        )
        build_chen_gong_2019_input(in_path, event_e, event_i, config=cfg, loop_num=1, seed=1)
        report.pass_("preprocessing build", str(in_path))
        in_summary = inspect_in_file(in_path, event_e, event_i, report)
        tree_path = output_dir / "debug_spikenet_in_tree.txt"
        tree_path.write_text("\n".join(h5_tree(in_path)), encoding="utf-8")
        report.pass_("in.h5 tree dump", str(tree_path))

    payload = {
        "event_e": event_summary_e,
        "event_i": event_summary_i,
        "in_h5": in_summary,
        "checks": [check.__dict__ for check in report.checks],
    }
    report_path = output_dir / "debug_preprocessing_report.json"
    write_json_report(report_path, payload)
    report.pass_("json report", str(report_path))
    report.print()
    return 1 if report.failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
